### ISSUE TITLE
sorcepath is wrong

### ISSUE THREAD

**Issue by skeeran** [philippfrenzel/yii2masonry#1]
sourcepath is wrong to assets is the error

i changed the path and it is working... maybe you can check... and correct it. 

```
i made it from  
public $sourcePath = '@philippfrenzel/yii2masonry/assets';

to

public $sourcePath = '@vendor/philippfrenzel/yii2masonry/philippfrenzel/yii2masonry/assets';
```

**Comment by philippfrenzel** [comment]
sorry my fault, didn't use this extension so my composer.json is "wrong" I'll update it tomorrow;) Thanks for reporting!

**Comment by philippfrenzel** [comment]
I will move to the bower packages, so the issue will be "gone" ;) pls. ensure that you have the latest composer-asset plugin installed while update runs;)

**Comment by philippfrenzel** [comment]
@skeeran moved to bower, so sourcePath is "new" -> will close this for now - Thanks for reporting!
