### ISSUE TITLE
height calculation is wrong

### ISSUE THREAD

**Issue by skeeran** [philippfrenzel/yii2masonry#2]
Hi,

i am having a problem with hight of the div(container) is only 20, through its looking mess.

```
<div id="w1" class="js-masonry" style="position: relative; height: 20px;">

```

thanks

**Comment by philippfrenzel** [comment]
Hi, pls check the plugin options on the original page, you can set height!

**Comment by skeeran** [comment]
i mean main container where the hight have to calculated depending on content, to set fixed hight is not right.

**Comment by philippfrenzel** [comment]
ok, got you, I'll take a look at this now and see why this happens _> as I set no height for the container
To understand better, can you send me the code of the view where you try to implement it?
Thanks!

**Comment by skeeran** [comment]
```
                     <?php \philippfrenzel\yii2masonry\yii2masonry::begin([
                        'clientOptions' => [
                            'columnWidth' => 300,
                            'itemSelector' => '.item'
                            ]
                    ]); ?>

                    <?= ListView::widget([
                        'dataProvider' => $dataProvider,
                        'layout' => "{summary}\n{items}</div></div>{pager}",
                        'itemOptions' => ['class' => 'item share share-self col0'],
                        'itemView' => function ($model, $key, $index, $widget) {
                            return $this->render('_view', ['model' => $model]);
                        },
                    ]) ?>

                    <?php \philippfrenzel\yii2masonry\yii2masonry::end(); ?>
```

when i remove in your yii2masonry.php file on line 50 the class

like this the hight is getting calculated

```
from
echo Html::beginTag('div', ['id' => $this->options['id'], 'class'=>'js-masonry']); //opens the container

to 
echo Html::beginTag('div', ['id' => $this->options['id']]); //opens the container
```

**Comment by philippfrenzel** [comment]
thanks! I'll check this! -> as the class is not mandantory.. Update will be available in about 10 hours;)

**Comment by philippfrenzel** [comment]
removed the class and now all container settings can be passed over by the options attribute during initialisation
