### ISSUE TITLE
Yii2 listview with masonry

### ISSUE THREAD

**Issue by skeeran** [philippfrenzel/yii2masonry#3]
hi, 

i am using trying to use this Extension with Listview from Yii2 then the issues are {summery} and {pagination} are not rendered correct ... because of the positions ... they are in background..

maybe u can implement this extension for yii2 listview also.

Thank you

**Comment by philippfrenzel** [comment]
I'll combine this extension with the listview ajaxscroll extension which dynamically loads new tiles... I'll write an example..:)

**Comment by skeeran** [comment]
amazing :D

**Comment by philippfrenzel** [comment]
kop/yii2-scroll-pager 
Just put the listview inside the begin and end and change the template
