### ISSUE TITLE
can't install this extension---bower-asset/masonry not found.

### ISSUE THREAD

**Issue by shi-yang** [philippfrenzel/yii2masonry#4]
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - philippfrenzel/yii2masonry dev-master requires bower-asset/masonry \* -> no
 matching package found.
    - philippfrenzel/yii2masonry 1.1.1 requires bower-asset/masonry \* -> no matc
hing package found.
    - philippfrenzel/yii2masonry 1.1 requires bower-asset/masonry \* -> no matchi
ng package found.
    - philippfrenzel/yii2masonry 1.0 requires bower-asset/masonry \* -> no matchi
ng package found.
    - Installation request for philippfrenzel/yii2masonry \* -> satisfiable by ph
ilippfrenzel/yii2masonry[1.0, 1.1, 1.1.1, dev-master].

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your min
  imum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion f
  or more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common
 problems.

**Comment by philippfrenzel** [comment]
ok, I'll check this and come back to you

**Comment by philippfrenzel** [comment]
ok, I think you might have an issue with not having the latest composer assets plugin from francois...
which version do you run?

composer global require "fxp/composer-asset-plugin:1.0.0-beta4"

Cheers Phil

**Comment by shi-yang** [comment]
okay. thanks.

**Comment by philippfrenzel** [comment]
is it working? I don't wanna close without a yes :)?

**Comment by shi-yang** [comment]
yes.
