### ISSUE TITLE
fix deps for stable tag 1.2.0

### ISSUE THREAD

**Issue by schmunk42** [philippfrenzel/yii2masonry#8]
I think this https://github.com/francoispluchino/composer-asset-plugin/issues/96 would be prevented on current `master`.

[Edit]
**I have update issues, which should be fixed first** - title updated.

**Comment by schmunk42** [comment]
Related: https://github.com/francoispluchino/composer-asset-plugin/issues/70

**Comment by philippfrenzel** [comment]
thanks - I'll fix it in about 2 hours! hope you are fine!

**Comment by schmunk42** [comment]
@philippfrenzel @francoispluchino Does the asset plugin parse the extra section of a every bower-asset and looks for a repo?

If no, this is not a fix - and it can currently only be fixed "by docs".
If yes, it may lead into issues like [described here](https://getcomposer.org/doc/faqs/why-can%27t-composer-load-repositories-recursively.md).

**Comment by francoispluchino** [comment]
It is for this reason that I have not automatized the adding of VCS repositories in the extra section.
